# Generated by Django 4.1 on 2022-08-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="password1",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register",
            name="password2",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register",
            name="username",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
