# Generated by Django 4.1 on 2022-08-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0003_register_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="register", name="user",),
    ]
