# Generated by Django 4.1 on 2022-08-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0005_register_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("email", models.EmailField(max_length=254)),
                ("born_date", models.DateField()),
                ("age", models.IntegerField()),
                ("phone_number", models.IntegerField()),
                ("city", models.CharField(max_length=50)),
                ("Country", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("password1", models.CharField(max_length=100)),
                ("password2", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(name="Register",),
    ]
