# Generated by Django 4.1 on 2022-08-30 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ProjectApp", "0007_registers_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("email", models.EmailField(max_length=254)),
                ("born_date", models.DateField()),
                ("age", models.IntegerField()),
                ("phone_number", models.IntegerField()),
                ("city", models.CharField(max_length=50)),
                ("Country", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("password1", models.CharField(max_length=100)),
                ("password2", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        default=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Registers",),
    ]
