# Generated by Django 4.1 on 2022-08-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0010_rename_register_registers"),
    ]

    operations = [
        migrations.RemoveField(model_name="registers", name="user",),
    ]
