# Generated by Django 4.1 on 2022-08-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0011_remove_registers_user"),
    ]

    operations = [
        migrations.RenameModel(old_name="Registers", new_name="Register",),
    ]
