# Generated by Django 4.1 on 2022-08-31 07:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ProjectApp", "0014_alter_register_user"),
    ]

    operations = [
        migrations.RenameModel(old_name="Register", new_name="UserProfile",),
    ]
