# Generated by Django 4.1 on 2022-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0016_alter_userprofile_country_alter_userprofile_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adddata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=60, null=True)),
                ("last_name", models.CharField(blank=True, max_length=60, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("born_date", models.DateField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("Country", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
