# Generated by Django 4.1 on 2022-08-31 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0017_adddata"),
    ]

    operations = [
        migrations.DeleteModel(name="Adddata",),
        migrations.RemoveField(model_name="userprofile", name="user",),
    ]
