# Generated by Django 4.1 on 2022-08-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0020_remove_userprofile_password1_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="Country",),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
