# Generated by Django 4.1 on 2022-08-31 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0021_remove_userprofile_country_userprofile_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="country", new_name="countries",
        ),
    ]
