# Generated by Django 4.1 on 2022-08-31 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0023_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="users",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ProjectApp.userprofile",
            ),
        ),
    ]
