# Generated by Django 4.1 on 2022-08-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0025_alter_photo_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="profile_pic",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
