# Generated by Django 4.1 on 2022-09-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0026_alter_photo_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
