# Generated by Django 4.1 on 2022-09-01 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0027_alter_photo_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(model_name="photo", name="users",),
        migrations.AddField(
            model_name="userprofile",
            name="photo",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ProjectApp.photo",
            ),
        ),
    ]
