# Generated by Django 4.1 on 2022-09-01 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0028_remove_photo_users_userprofile_photo"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="photo",),
        migrations.AddField(
            model_name="photo",
            name="users",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ProjectApp.userprofile",
            ),
        ),
    ]
