# Generated by Django 4.1 on 2022-09-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0032_remove_photo_users_userprofile_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=60, null=True)),
                ("last_name", models.CharField(blank=True, max_length=60, null=True)),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField(max_length=499)),
            ],
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
