# Generated by Django 4.1 on 2022-09-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0033_contact_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
