# Generated by Django 4.1 on 2022-09-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0035_alter_contact_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
