# Generated by Django 4.1 on 2022-09-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0037_search_alter_photo_profile_pic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(name="Search",),
    ]
