# Generated by Django 4.1 on 2022-09-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0039_search_alter_userprofile_city"),
    ]

    operations = [
        migrations.RenameModel(old_name="Search", new_name="City",),
    ]
