# Generated by Django 4.1 on 2022-09-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectApp", "0040_rename_search_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Band",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="bands", to="ProjectApp.userprofile"
                    ),
                ),
            ],
        ),
    ]
